[workspace]
resolver = "2"
members = ["src-tauri"]

[workspace.package]
version = "0.1.0"
description = "Configurator for Dygma keyboards"
authors = ["Matthew Wilding <mbwilding@gmail.com"]
edition = "2021"
